### ISSUE TITLE
PIB Error

### ISSUE THREAD

**Issue by nkdnnlr** [duguyue100/pyaer#15]
Hi
Running davis346_test.py gives me the following error:
```
Device ID: 1
Device is master.
Device Serial Number: 00000065
Device String: DAVIS ID-1 SN-00000065 [6:5]
Device USB bus Number: 6
Device USB device address: 5
Device size X: 346
Device size Y: 260
Logic Version: 18
Background Activity Filter: True
2019-07-31 13:59:57 (TZ+0200): ERROR: DAVIS ID-1 SN-00000065 [6:5]: Error message: 'PIB Error: Other PIB Error occurred!' (code 26 at time 5521).
2019-07-31 13:59:57 (TZ+0200): ERROR: DAVIS ID-1 SN-00000065 [6:5]: Error message: 'PIB Error: Other PIB Error occurred!' (code 26 at time 5526).
Traceback (most recent call last):
  File "davis346_test.py", line 33, in <module>
    device.set_bias_from_json("./scripts/configs/davis346_config.json")
  File "/home/dedennler/anaconda3/envs/E2VID/lib/python3.7/site-packages/pyaer/davis.py", line 213, in set_bias_from_json
    self.set_bias(bias_obj)
  File "/home/dedennler/anaconda3/envs/E2VID/lib/python3.7/site-packages/pyaer/davis.py", line 251, in set_bias
    bias_obj["aps_enabled"])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by duguyue100** [comment]
Hi, did you run `make davis346-test` or running the script directly?
Furthermore, did you install the `libcaer` as suggested in the README page?

**Comment by nkdnnlr** [comment]
Thanks, it works by running `make davis346-test` first instead of running the scripts directly. 
Solved.
